### ISSUE TITLE
"fatal error: concurrent map read and map write" scanning repository

### ISSUE THREAD

**Issue by rhencke** [zricethezav/gitleaks#124]
Version: Built from master (87d916fc24921cde82ecb641d40c1db9d6df81fb as of writing)
OS: macOS 10.14
Go: go version go1.11.1 darwin/amd64

When running 'gitleaks' against a local repository I have (`gitleaks --repo-path=path/to/my/repo`), gitleaks panics with message listed below.

Unfortunately, the repository is private so I cannot share it, but if there's any information I can give to help narrow this down or steps I can take, I am happy to.  Thank you.

```
fatal error: concurrent map read and map write

goroutine 37 [running]:
runtime.throw(0x166cf3b, 0x21)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/panic.go:608 +0x72 fp=0xc000d43178 sp=0xc000d43148 pc=0x102c342
runtime.mapaccess2_fast64(0x15888c0, 0xc00001f800, 0x32ec0d, 0xc000d2e240, 0x3f)
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/map_fast64.go:61 +0x1a8 fp=0xc000d431a0 sp=0xc000d43178 pc=0x1012668
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile.(*MemoryIndex).FindHash(0xc000252880, 0x32ec0d, 0x0, 0x0, 0x0, 0x14, 0xf03e1f0aa05a57fc)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile/idxfile.go:177 +0x6b fp=0xc000d43200 sp=0xc000d431a0 pc=0x140c47b
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem.(*ObjectStorage).decodeObjectAt(0xc000148f68, 0x16f44e0, 0xc000d301c0, 0x16f3d60, 0xc000252880, 0x32ec0d, 0x0, 0x0, 0x662e5d6c66d49473, 0x32ec0d)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go:301 +0x56 fp=0xc000d43290 sp=0xc000d43200 pc=0x1437676
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem.(*ObjectStorage).getFromPackfile(0xc000148f68, 0x2f9db7ce84927f1f, 0x66d49473dcedf309, 0x662e5d6c, 0x0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go:293 +0x2cc fp=0xc000d43398 sp=0xc000d43290 pc=0x143749c
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem.(*ObjectStorage).EncodedObject(0xc000148f68, 0x9db7ce84927f1f02, 0xd49473dcedf3092f, 0x662e5d6c66, 0x0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go:174 +0x3f5 fp=0xc000d43438 sp=0xc000d43398 pc=0x1436c05
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.GetTree(0x1f852a0, 0xc000148f50, 0x2f9db7ce84927f1f, 0x66d49473dcedf309, 0x662e5d6c, 0x203000, 0x203000, 0x1020f28)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:45 +0x4e fp=0xc000d43488 sp=0xc000d43438 pc=0x13bb95e
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*TreeWalker).Next(0xc000d436c0, 0xc000cfe5a0, 0x9, 0xc000d62140, 0x14, 0x84927f1f00004000, 0xdcedf3092f9db7ce, 0x662e5d6c66d49473, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:408 +0x56f fp=0xc000d435c8 sp=0xc000d43488 pc=0x13bdf7f
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.transformChildren(0xc000c44230, 0x15efbc0, 0xc001dec701, 0x1b73280, 0x28, 0x38)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/treenoder.go:105 +0x21d fp=0xc000d43720 sp=0xc000d435c8 pc=0x13be9bd
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*treeNoder).Children(0xc000cfe3c0, 0x1b73280, 0x1f41b00, 0xc000001c80, 0x203000, 0x1020f28)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/treenoder.go:87 +0x61 fp=0xc000d43760 sp=0xc000d43720 pc=0x13be6b1
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie/internal/frame.New(0x16f3760, 0xc000cfe3c0, 0x48, 0x48, 0xc000cfe460)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie/internal/frame/frame.go:29 +0x3b fp=0xc000d437e0 sp=0xc000d43760 pc=0x133fcfb
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie.newIter(0x16f3760, 0xc000cfe3c0, 0x0, 0x0, 0x0, 0x15efc80, 0x1, 0xc000cfe460)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie/iter.go:90 +0x87 fp=0xc000d43840 sp=0xc000d437e0 pc=0x1342db7
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie.NewIter(0x16f3760, 0xc000cfe3c0, 0x1, 0x16ec5c0, 0xc00006a060)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie/iter.go:71 +0x46 fp=0xc000d43890 sp=0xc000d43840 pc=0x1342c26
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie.newDoubleIter(0x16f3760, 0xc000cfe3c0, 0x16f3760, 0xc000cfe410, 0x167ecf8, 0xc000001c80, 0x1000, 0x1000)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie/doubleiter.go:43 +0x67 fp=0xc000d43940 sp=0xc000d43890 pc=0x1341ed7
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie.DiffTreeContext(0x16f2380, 0xc0000260c0, 0x16f3760, 0xc000cfe3c0, 0x16f3760, 0xc000cfe410, 0x167ecf8, 0x13bb9bc, 0x1f852a0, 0xc000148f50, ...)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/merkletrie/difftree.go:277 +0x96 fp=0xc000d439d0 sp=0xc000d43940 pc=0x1341046
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.DiffTreeContext(0x16f2380, 0xc0000260c0, 0xc000c44230, 0xc000cfe320, 0x8a0f72a6f3d94d5e, 0x3faba7ce, 0xc000cfe320, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/difftree.go:28 +0x157 fp=0xc000d43a58 sp=0xc000d439d0 pc=0x13b5b37
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Tree).PatchContext(0xc000c44230, 0x16f2380, 0xc0000260c0, 0xc000cfe320, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:316 +0x4d fp=0xc000d43ab0 sp=0xc000d43a58 pc=0x13bd89d
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).PatchContext(0xc000bf80f0, 0x16f2380, 0xc0000260c0, 0xc000bf8000, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:92 +0xb5 fp=0xc000d43b00 sp=0xc000d43ab0 pc=0x13b0c55
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).Patch(0xc000bf80f0, 0xc000bf8000, 0xc000027820, 0xc0000304d0, 0xc000bf80f0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:97 +0x4d fp=0xc000d43b48 sp=0xc000d43b00 pc=0x13b0cfd
main.auditGitReference.func1.1(0xc000027820, 0xc0000304d0, 0xc00015a540, 0x165d595, 0x1, 0xc000027830, 0xc00013d1e0, 0xc000bf80f0, 0xc000bf8000)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:564 +0xc2 fp=0xc000d43f98 sp=0xc000d43b48 pc=0x14fae92
runtime.goexit()
	/usr/local/Cellar/go/1.11.1/libexec/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000d43fa0 sp=0xc000d43f98 pc=0x1058911
created by main.auditGitReference.func1
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:521 +0x3af

goroutine 1 [chan send]:
main.auditGitReference.func1(0xc000bf83c0, 0xc000bf83c0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:520 +0x32b
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*commitPreIterator).ForEach(0xc00012e720, 0xc000a1ad20, 0x16f1600, 0xc00012e720)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit_walker.go:103 +0x65
main.auditGitReference(0xc0000af1d0, 0xc00015a540, 0x0, 0x0, 0xc00013c1c0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:499 +0x279
main.auditGitRepo(0xc0000af1d0, 0x0, 0x0, 0xc00011ddb0, 0xd93f1f82, 0xbed1d93f1f82)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:470 +0x23c
main.run(0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:306 +0x105
main.main()
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:251 +0xea

goroutine 36 [runnable]:
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile.(*idxfileEntryIter).Next(0xc001dd4020, 0xc00001f800, 0xc35fa1, 0xc001651ae8)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile/idxfile.go:266 +0x25a
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile.(*MemoryIndex).genOffsetHash(0xc000252880, 0x142c196, 0xc00013c9c0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile/idxfile.go:200 +0x110
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile.(*MemoryIndex).FindHash(0xc000252880, 0xe30e46, 0x0, 0x0, 0x0, 0x14, 0xf03e1f0aa05a57fc)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/idxfile/idxfile.go:172 +0x111
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem.(*ObjectStorage).decodeObjectAt(0xc000148f68, 0x16f44e0, 0xc00000cae0, 0x16f3d60, 0xc000252880, 0xe30e46, 0x0, 0x0, 0xf29030d0779f9e95, 0xe30e46)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go:301 +0x56
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem.(*ObjectStorage).getFromPackfile(0xc000148f68, 0x304b930673e10c87, 0x779f9e95b1674781, 0xf29030d0, 0x0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go:293 +0x2cc
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem.(*ObjectStorage).EncodedObject(0xc000148f68, 0x4b930673e10c8703, 0x9f9e95b167478130, 0xf29030d077, 0x0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/storage/filesystem/object.go:174 +0x3f5
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.GetBlob(0x1f852a0, 0xc000148f50, 0x304b930673e10c87, 0x779f9e95b1674781, 0xf29030d0, 0x73e10c87000081a4, 0xb1674781304b9306, 0xf29030d0779f9e95)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/blob.go:23 +0x4e
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*FileIter).Next(0xc000ccbd88, 0x167ecf0, 0xc000ccbd88, 0x100df28)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/file.go:100 +0x136
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*FileIter).ForEach(0xc0000d1d88, 0xc0000d1d00, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/file.go:116 +0x61
main.auditGitReference.func1.1(0xc000027820, 0xc0000304d0, 0xc00015a540, 0x165d595, 0x1, 0xc000027830, 0xc00013d1e0, 0xc000bf8000, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:537 +0x9f9
created by main.auditGitReference.func1
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:521 +0x3af

goroutine 38 [runnable]:
bufio.(*Reader).ReadBytes(0xc001e1e060, 0xc000044520, 0xc001dc9878, 0x1014975, 0xc001e1e060, 0xc001dc9968, 0x58)
	/usr/local/Cellar/go/1.11.1/libexec/src/bufio/bufio.go:442 +0x287
bufio.(*Reader).ReadString(0xc001e1e060, 0xc001e1e020, 0xc001dc9968, 0xc001e22000, 0x1000, 0x1000)
	/usr/local/Cellar/go/1.11.1/libexec/src/bufio/bufio.go:459 +0x38
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Tree).Decode(0xc001e20000, 0x16f3d00, 0xc000cf2100, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:224 +0x22f
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.DecodeTree(0x1f852a0, 0xc000148f50, 0x16f3d00, 0xc000cf2100, 0x16f3d00, 0xc000cf2100, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:57 +0x73
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.GetTree(0x1f852a0, 0xc000148f50, 0x8d39453cbff2a2d5, 0x232664e5d65d8abe, 0xded131e9, 0xc000ca0230, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:50 +0xac
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).Tree(0xc000bf80f0, 0xc000ca0230, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:76 +0x56
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).PatchContext(0xc000bf81e0, 0x16f2380, 0xc0000260c0, 0xc000bf80f0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:87 +0x5a
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).Patch(0xc000bf81e0, 0xc000bf80f0, 0xc000027820, 0xc0000304d0, 0xc000bf81e0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:97 +0x4d
main.auditGitReference.func1.1(0xc000027820, 0xc0000304d0, 0xc00015a540, 0x165d595, 0x1, 0xc000027830, 0xc00013d1e0, 0xc000bf81e0, 0xc000bf80f0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:564 +0xc2
created by main.auditGitReference.func1
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:521 +0x3af

goroutine 39 [runnable]:
bytes.makeSlice.func1()
	/usr/local/Cellar/go/1.11.1/libexec/src/bytes/buffer.go:226 +0x69
bytes.makeSlice(0x600, 0xc001df8000, 0x600, 0x600)
	/usr/local/Cellar/go/1.11.1/libexec/src/bytes/buffer.go:231 +0x8c
bytes.(*Buffer).grow(0xc000c707e0, 0x200, 0x200)
	/usr/local/Cellar/go/1.11.1/libexec/src/bytes/buffer.go:144 +0x15a
bytes.(*Buffer).ReadFrom(0xc000c707e0, 0x2d65230, 0xc000c443c0, 0x1f9e698, 0xc000c707e0, 0x141d001)
	/usr/local/Cellar/go/1.11.1/libexec/src/bytes/buffer.go:204 +0x4b
io.copyBuffer(0x16ec2c0, 0xc000c707e0, 0x2d65230, 0xc000c443c0, 0xc001de2000, 0x8000, 0x8000, 0x15b4ea0, 0xc000478500, 0x2d65230)
	/usr/local/Cellar/go/1.11.1/libexec/src/io/io.go:388 +0x303
io.CopyBuffer(0x16ec2c0, 0xc000c707e0, 0x2d65230, 0xc000c443c0, 0xc001de2000, 0x8000, 0x8000, 0xc000086900, 0xc000d64000, 0x16014a0)
	/usr/local/Cellar/go/1.11.1/libexec/src/io/io.go:375 +0x82
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Scanner).copyObject(0xc000cfe280, 0x16ec2c0, 0xc000c707e0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/scanner.go:297 +0x2a4
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Scanner).NextObject(0xc000cfe280, 0x16ec2c0, 0xc000c707e0, 0x0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/scanner.go:272 +0xa2
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Packfile).fillOFSDeltaObjectContent(0xc000cfe2d0, 0x16f3d00, 0xc00015a1c0, 0x39c88, 0x7a, 0xc000d47780)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/packfile.go:353 +0x72
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Packfile).getNextObject(0xc000cfe2d0, 0xc000d2e180, 0x0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/packfile.go:303 +0x19e
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Packfile).getObjectContent(0xc000cfe2d0, 0x4d66a, 0x0, 0x0, 0x16f44e0, 0xc000d30100)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/packfile.go:283 +0xd3
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*FSObject).Reader(0xc000dae000, 0x660, 0x9f0205c05eda1cd5, 0xc0ce43aad0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/fsobject.go:66 +0x18a
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Tree).Decode(0xc000cfe230, 0x16f3dc0, 0xc000dae000, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:216 +0x115
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.DecodeTree(0x1f852a0, 0xc000148f50, 0x16f3dc0, 0xc000dae000, 0x16f3dc0, 0xc000dae000, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:57 +0x73
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.GetTree(0x1f852a0, 0xc000148f50, 0xe1fce1fc99ff517e, 0x9f0205c05eda1cd5, 0xce43aad0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:50 +0xac
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).Tree(0xc000bf82d0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:76 +0x56
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).PatchContext(0xc000bf82d0, 0x16f2380, 0xc0000260c0, 0xc000bf81e0, 0x0, 0x0, 0x0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:82 +0x2f
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).Patch(0xc000bf82d0, 0xc000bf81e0, 0xc000027820, 0xc0000304d0, 0xc000bf82d0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:97 +0x4d
main.auditGitReference.func1.1(0xc000027820, 0xc0000304d0, 0xc00015a540, 0x165d595, 0x1, 0xc000027830, 0xc00013d1e0, 0xc000bf82d0, 0xc000bf81e0)
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:564 +0xc2
created by main.auditGitReference.func1
	/Users/robert.hencke/src/github.com/zricethezav/gitleaks/main.go:521 +0x3af
```

**Comment by zricethezav** [comment]
https://github.com/src-d/go-git/issues/457 looks like go-git does not support concurrency when running against a local repo. Try running this with `--max-go=1`. I'll make it a default next release

**Comment by zricethezav** [comment]
Forcing a single thread run if running gitleaks against a local repo: https://github.com/zricethezav/gitleaks/releases/tag/v1.16.0
