### ISSUE TITLE
fatal error: runtime: out of memory due at --report

### ISSUE THREAD

**Issue by arbazkiraak** [zricethezav/gitleaks#168]
Hi @zricethezav ,

```
→ gitleaks --repo=https://github.com/pricelinelabs/design-system -e 5 --depth=100 --report=test.json
INFO[2018-12-28T09:12:18Z] cloning https://github.com/pricelinelabs/design-system 
Enumerating objects: 304, done.
Counting objects: 100% (304/304), done.
Compressing objects: 100% (146/146), done.
Total 10075 (delta 136), reused 228 (delta 113), pack-reused 9771
INFO[2018-12-28T09:13:17Z] writing report to test.json                  
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb09987, 0x16)
        /usr/local/go/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc457830000, 0x247f0000, 0xc420000100, 0xef9738)
        /usr/local/go/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0xee0060, 0x247f0000, 0x67aba1)
        /usr/local/go/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0xee0060, 0x123f2, 0x0)
        /usr/local/go/src/runtime/mheap.go:907 +0x60
runtime.(*mheap).allocSpanLocked(0xee0060, 0x123f2, 0xef9748, 0x7f86d91e5dd8)
        /usr/local/go/src/runtime/mheap.go:820 +0x301
runtime.(*mheap).alloc_m(0xee0060, 0x123f2, 0x7f86da990101, 0x4521b0)
        /usr/local/go/src/runtime/mheap.go:686 +0x118
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:753 +0x4d
runtime.(*mheap).alloc(0xee0060, 0x123f2, 0x7f86d9010101, 0x415a2c)
        /usr/local/go/src/runtime/mheap.go:752 +0x8a
runtime.largeAlloc(0x247e3cf4, 0x450101, 0x7f86da99a6c8)
        /usr/local/go/src/runtime/malloc.go:826 +0x94
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:721 +0x46
runtime.systemstack(0x7ffc00000000)
        /usr/local/go/src/runtime/asm_amd64.s:409 +0x79
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1175

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:363 fp=0xc4210b1460 sp=0xc4210b1458 pc=0x454020
runtime.mallocgc(0x247e3cf4, 0x9c72e0, 0x411a01, 0xc4210b1538)
        /usr/local/go/src/runtime/malloc.go:720 +0x8a2 fp=0xc4210b1500 sp=0xc4210b1460 pc=0x412002
runtime.makeslice(0x9c72e0, 0x247e3cf4, 0x247e3cf4, 0x0, 0x25, 0xc4210b15f8)
        /usr/local/go/src/runtime/slice.go:61 +0x77 fp=0xc4210b1530 sp=0xc4210b1500 pc=0x4409e7
bytes.makeSlice(0x247e3cf4, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:230 +0x6d fp=0xc4210b1570 sp=0xc4210b1530 pc=0x4d308d
bytes.(*Buffer).grow(0xc430ed78c0, 0x6a, 0x4)
        /usr/local/go/src/bytes/buffer.go:144 +0x151 fp=0xc4210b15c0 sp=0xc4210b1570 pc=0x4d2a41
bytes.(*Buffer).WriteString(0xc430ed78c0, 0xc42d7c963b, 0x6a, 0x0, 0x0, 0x0)
        /usr/local/go/src/bytes/buffer.go:186 +0xd9 fp=0xc4210b15f0 sp=0xc4210b15c0 pc=0x4d2e29
encoding/json.(*encodeState).string(0xc430ed78c0, 0xc42d672000, 0x158512, 0xc42d672001)
        /usr/local/go/src/encoding/json/encode.go:886 +0xea fp=0xc4210b1650 sp=0xc4210b15f0 pc=0x67eb0a
encoding/json.stringEncoder(0xc430ed78c0, 0x9c70e0, 0xc432bbb9c0, 0x198, 0x100)
        /usr/local/go/src/encoding/json/encode.go:602 +0x214 fp=0xc4210b1710 sp=0xc4210b1650 pc=0x67c784
encoding/json.(*structEncoder).encode(0xc431c1c930, 0xc430ed78c0, 0xacaf00, 0xc432bbb9c0, 0x199, 0x100)
        /usr/local/go/src/encoding/json/encode.go:639 +0x255 fp=0xc4210b1870 sp=0xc4210b1710 pc=0x67cd45
encoding/json.(*structEncoder).(encoding/json.encode)-fm(0xc430ed78c0, 0xacaf00, 0xc432bbb9c0, 0x199, 0xac0100)
        /usr/local/go/src/encoding/json/encode.go:653 +0x64 fp=0xc4210b18b0 sp=0xc4210b1870 pc=0x6878e4
encoding/json.(*arrayEncoder).encode(0xc431b606e8, 0xc430ed78c0, 0x9baf00, 0xc431c67ee0, 0x97, 0x100)
        /usr/local/go/src/encoding/json/encode.go:761 +0xdc fp=0xc4210b1908 sp=0xc4210b18b0 pc=0x67debc
encoding/json.(*arrayEncoder).(encoding/json.encode)-fm(0xc430ed78c0, 0x9baf00, 0xc431c67ee0, 0x97, 0xc430ed0100)
        /usr/local/go/src/encoding/json/encode.go:768 +0x64 fp=0xc4210b1948 sp=0xc4210b1908 pc=0x687a64
encoding/json.(*sliceEncoder).encode(0xc431b606f0, 0xc430ed78c0, 0x9baf00, 0xc431c67ee0, 0x97, 0x9b0100)
        /usr/local/go/src/encoding/json/encode.go:735 +0xc1 fp=0xc4210b1988 sp=0xc4210b1948 pc=0x67dbe1
encoding/json.(*sliceEncoder).(encoding/json.encode)-fm(0xc430ed78c0, 0x9baf00, 0xc431c67ee0, 0x97, 0xc431c60100)
        /usr/local/go/src/encoding/json/encode.go:747 +0x64 fp=0xc4210b19c8 sp=0xc4210b1988 pc=0x6879e4
encoding/json.(*encodeState).reflectValue(0xc430ed78c0, 0x9baf00, 0xc431c67ee0, 0x97, 0x100)
        /usr/local/go/src/encoding/json/encode.go:325 +0x82 fp=0xc4210b1a00 sp=0xc4210b19c8 pc=0x67aba2
encoding/json.(*encodeState).marshal(0xc430ed78c0, 0x9baf00, 0xc431c67ee0, 0xc4200a0100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:298 +0xa5 fp=0xc4210b1a38 sp=0xc4210b1a00 pc=0x67a895
encoding/json.Marshal(0x9baf00, 0xc431c67ee0, 0x7f86da99a6c8, 0x0, 0x1, 0xc42b724cd0, 0xc4210b1af0)
        /usr/local/go/src/encoding/json/encode.go:161 +0x5f fp=0xc4210b1a80 sp=0xc4210b1a38 pc=0x67a29f
encoding/json.MarshalIndent(0x9baf00, 0xc431c67ee0, 0x0, 0x0, 0xafc655, 0x1, 0xc420c93f40, 0xc430f39c48, 0xc420338040, 0xc429b34532, ...)
        /usr/local/go/src/encoding/json/encode.go:172 +0x3f fp=0xc4210b1b00 sp=0xc4210b1a80 pc=0x67a37f
main.writeReport(0xc432a24000, 0x7c33, 0x9579, 0x0, 0x0)
        /root/go_projects/src/github.com/zricethezav/gitleaks/main.go:363 +0x5e2 fp=0xc4210b1e18 sp=0xc4210b1b00 pc=0x9429f2
main.main()
        /root/go_projects/src/github.com/zricethezav/gitleaks/main.go:270 +0x419 fp=0xc4210b1f88 sp=0xc4210b1e18 pc=0x941a29
runtime.main()
        /usr/local/go/src/runtime/proc.go:198 +0x212 fp=0xc4210b1fe0 sp=0xc4210b1f88 pc=0x42ca92
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4210b1fe8 sp=0xc4210b1fe0 pc=0x456bb1

goroutine 33 [IO wait]:
internal/poll.runtime_pollWait(0x7f86da94ee30, 0x72, 0xc420057760)
        /usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc4201fe218, 0x72, 0xffffffffffffff00, 0xb68260, 0xe89568)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc4201fe218, 0xc4206b2000, 0x8000, 0x8000)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc4201fe200, 0xc4206b2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:157 +0x17d
net.(*netFD).Read(0xc4201fe200, 0xc4206b2000, 0x8000, 0x8000, 0xc4200578e0, 0xc4200578e8, 0x411a59)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc4200a4088, 0xc4206b2000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:176 +0x6a
crypto/tls.(*block).readFromUntil(0xc42020a360, 0x7f86da90a020, 0xc4200a4088, 0x5, 0xc4200a4088, 0x8)
        /usr/local/go/src/crypto/tls/conn.go:493 +0x96
crypto/tls.(*Conn).readRecord(0xc4200f6380, 0xb24e17, 0xc4200f64a0, 0x452dd0)
        /usr/local/go/src/crypto/tls/conn.go:595 +0xe0
crypto/tls.(*Conn).Read(0xc4200f6380, 0xc4200c3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1156 +0x100
net/http.(*persistConn).Read(0xc4200bd9e0, 0xc4200c3000, 0x1000, 0x1000, 0xc420057b98, 0x405195, 0xc420082840)
        /usr/local/go/src/net/http/transport.go:1453 +0x136
bufio.(*Reader).fill(0xc42001e600)
        /usr/local/go/src/bufio/bufio.go:100 +0x11e
bufio.(*Reader).Peek(0xc42001e600, 0x1, 0x0, 0x0, 0x0, 0xc420082720, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0x3a
net/http.(*persistConn).readLoop(0xc4200bd9e0)
        /usr/local/go/src/net/http/transport.go:1601 +0x185
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1237 +0x95a

goroutine 34 [select]:
net/http.(*persistConn).writeLoop(0xc4200bd9e0)
        /usr/local/go/src/net/http/transport.go:1822 +0x14b
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1238 +0x97f
```

```
./gitleaks --version
1.22.0
```

* Trying without `--report` argument.

```
→ gitleaks --repo=https://github.com/pricelinelabs/design-system -e 5 --depth=100
INFO[2018-12-28T09:34:07Z] cloning https://github.com/pricelinelabs/design-system 
Enumerating objects: 304, done.
Counting objects: 100% (304/304), done.
Compressing objects: 100% (146/146), done.
Total 10075 (delta 136), reused 228 (delta 113), pack-reused 9771
WARN[2018-12-28T09:35:07Z] 32125 leaks detected. 391 commits inspected in 59 seconds 299 milliseconds 
```

* I Believe Error caused due to `writing of large number of leaks` into json file. Is there any way to fix or skip it if it has large amount of `leaks` or limit the no of leaks to some amount if results are large, So that tool continues to hunt next repos.

Awaiting for the response .

**Comment by rudrasingh99** [comment]
@milo-minderbinder  @zricethezav facing same issues.

**Comment by milo-minderbinder** [comment]
@zricethezav I did some testing and when running with the options given above, a memory profile does indeed seem to show that `writeReport()` is the likely culprit:
![image](https://user-images.githubusercontent.com/10577399/50660524-05d25380-0f6e-11e9-80e8-371c600fc00f.png)
![image](https://user-images.githubusercontent.com/10577399/50660623-74afac80-0f6e-11e9-9ffa-675add003f0c.png)

**Comment by zricethezav** [comment]
@arbazkiraak Thanks for bringing this to my attention.
@milo-minderbinder Thank you for the analysis.

Gitleaks currently appends to a global slice of leaks. We could change this so that if a leak is encountered, log it (if verbose option is turned on), and send the leak to a queue that writes to a report file rather than waiting until the audit it completed to write. 

Thoughts?

**Comment by arbazkiraak** [comment]
Thanks, @milo-minderbinder for detailed analysis on the issue.

Please push the fix into main branch origin.

**Comment by zricethezav** [comment]
merged
