### ISSUE TITLE
Panicking when running in a subdirectory with --repo-path

### ISSUE THREAD

**Issue by merikan** [zricethezav/gitleaks#180]
Version: 1.24.0
When running gitleaks in a subdirectory of a repository a panic is thrown. 

Hi
I usually run gitleaks against my local git repos with '--repo-path .' Sometimes I'm in a subdirectory of the repo and then gitleaks fails with a panic.

```
$ gitleaks --repo-path . -v
INFO[2019-02-12T20:00:54+01:00] opening .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x156b969]

goroutine 1 [running]:
main.auditGitRepo(0xc0000cd680, 0x0, 0x0, 0xc00013ddb0, 0xa6bf2f8e, 0x13ab7a6bf2f8e)
        /Users/zrice/go/src/github.com/zricethezav/gitleaks/main.go:487 +0x1a9
main.run(0x0, 0x0, 0x0, 0x0, 0x0)
        /Users/zrice/go/src/github.com/zricethezav/gitleaks/main.go:317 +0x125
main.main()
        /Users/zrice/go/src/github.com/zricethezav/gitleaks/main.go:264 +0xea
```

It would be nice if the exception was more descriptive or even better if gitleaks started searching from the root of the repository (git rev-parse --show-toplevel).

Thanks for this awesome tool 👍

**Comment by mide** [comment]
I'm also able to reproduce this when specifying a directory that doesn't exist. I'm running version `1.24.0`. 


```
gitleaks --verbose --repo-path=fakepath
INFO[2019-05-21T12:48:25-04:00] opening fakepath
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15b7d94]

goroutine 1 [running]:
main.auditGitRepo(0xc0000c4eb0, 0x0, 0x0, 0x104ad74, 0x105ae20, 0xc00013bd70)
  ...redacted...gitleaks/main.go:487 +0x204
main.run(0x0, 0x0, 0x0, 0x0, 0x0)
  ...redacted...gitleaks/main.go:317 +0x122
main.main()
  ...redacted...gitleaks/main.go:264 +0x133
```

**Comment by zricethezav** [comment]
Just tested with v2.0.0 and it works as intended. I get an error message saying `unable to open .` and it fails gracefully. For reference:
```
~/go/src/github.com/zricethezav/gitleaks (master) $ cd build/
~/go/src/github.com/zricethezav/gitleaks/build (master) $ gitleaks --repo-path . -v
INFO[2019-05-28T16:49:06-05:00] opening .
ERRO[2019-05-28T16:49:06-05:00] unable to open .
INFO[2019-05-28T16:49:06-05:00] 0 leaks detected. 0 commits inspected in 3 milliseconds
```

Implementing a feature to do `--show-toplevel` would be interesting and I can do some research on that. Might not be possible with the go-git though.
