### ISSUE TITLE
Run time error when scanning large org w/ --report (csv) - out of memory

### ISSUE THREAD

**Issue by fr0stedfl4ke** [zricethezav/gitleaks#232]
Hi,

I seemed to receive a runtime error when scanning an org with 130 or so repo's. These repo's can be around 500 mb - 2 GB in size. I setup a screen from my VPS, set the --report perimeter and ended up just piping out the tool output into a .txt file so I can tail the progress when I log back in. It seemed to run very well (up to 6 hours) up to a certain point and just ended up panicking and crashing on me. While, I did receive a few "recovering from panic on commit" issues from the output... the only output I received in screen was this. 

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xbb3e46, 0x16)
        /usr/local/go/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc3b8000000, 0x4000000, 0x11740d8)
        /usr/local/go/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0x115b7e0, 0x70000, 0x115b7f0, 0x38)
        /usr/local/go/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0x115b7e0, 0x38, 0x0)
        /usr/local/go/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0x115b7e0, 0x38, 0x11740e8, 0x2030ed00000000)
        /usr/local/go/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0x115b7e0, 0x38, 0x101, 0x7f4440b80fff)
        /usr/local/go/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0x115b7e0, 0x38, 0x7f4440010101, 0x7f44800af3e8)
        /usr/local/go/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x6f612, 0x450101, 0x7f44800af3e8)
        /usr/local/go/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1153

(continues on)......................

github.com/zricethezav/gitleaks/src.auditGithubRepos(0xc0000b4630, 0x0, 0x0, 0xc0000c7db0, 0x5642fb)
github.com/zricethezav/gitleaks/src.auditGithubRepos(0xc0000b4630, 0x0, 0x0, 0xc0000c7db0, 0x5642fb)
github.com/zricethezav/gitleaks/src.auditGithubRepos(0xc0000b4630, 0x0, 0x0, 0xc0000c7db0, 0x5642fb)
        /home/admin/Projects/gitleaks/src/github.com/zricethezav/gitleaks/src/github.go:166 +0x6ef f
github.com/zricethezav/gitleaks/src.Run(0xc0000b2b40, 0x0, 0x0, 0x0)
        /home/admin/Projects/gitleaks/src/github.com/zricethezav/gitleaks/src/core.go:91 +0x3e1 fp=0
main.main()
        /home/admin/Projects/gitleaks/src/github.com/zricethezav/gitleaks/main.go:12 +0x39 fp=0xc000
runtime.main()
        /usr/local/go/src/runtime/proc.go:200 +0x20c fp=0xc000703fe0 sp=0xc000703f98 pc=0x42f45c
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc000703fe8 sp=0xc000703fe0 pc=0x4596b1

goroutine 334237 [select, 1 minutes]:
net/http.(*persistConn).writeLoop(0xc088118120)
        /usr/local/go/src/net/http/transport.go:1976 +0x113
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1358 +0xb0d

goroutine 334236 [IO wait]:
internal/poll.runtime_pollWait(0x7fbd118df048, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc084ff9a18, 0x72, 0xde00, 0xdeed, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc084ff9a00, 0xc0e454a000, 0xdeed, 0xdeed, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc084ff9a00, 0xc0e454a000, 0xdeed, 0xdeed, 0x203098, 0x40d489, 0xc2555515c0)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0005ee8f0, 0xc0e454a000, 0xdeed, 0xdeed, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:177 +0x69
crypto/tls.(*atLeastReader).Read(0xc261b7c500, 0xc0e454a000, 0xdeed, 0xdeed, 0xc2555515c0, 0x4147ce,
        /usr/local/go/src/crypto/tls/conn.go:761 +0x60
bytes.(*Buffer).ReadFrom(0xc0c35cf058, 0xc7f840, 0xc261b7c500, 0x40b595, 0xabdf60, 0xb81cc0)
        /usr/local/go/src/bytes/buffer.go:207 +0xbd
crypto/tls.(*Conn).readFromUntil(0xc0c35cee00, 0xc805c0, 0xc0005ee8f0, 0x5, 0xc0005ee8f0, 0x203016)
        /usr/local/go/src/crypto/tls/conn.go:783 +0xf8
crypto/tls.(*Conn).readRecordOrCCS(0xc0c35cee00, 0xbd0c00, 0xc0c35cef38, 0xc000055b88)
        /usr/local/go/src/crypto/tls/conn.go:590 +0x125
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:558
crypto/tls.(*Conn).Read(0xc0c35cee00, 0xc0da63a000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1236 +0x137
net/http.(*persistConn).Read(0xc088118120, 0xc0da63a000, 0x1000, 0x1000, 0xc000055c88, 0x406bc5, 0xc
        /usr/local/go/src/net/http/transport.go:1524 +0x7b
bufio.(*Reader).fill(0xc0da632a20)
        /usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).Peek(0xc0da632a20, 0x1, 0x0, 0x0, 0x1, 0xc1769b5c00, 0x0)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc088118120)
        /usr/local/go/src/net/http/transport.go:1677 +0x1a3
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:1357 +0xae8

**Comment by fr0stedfl4ke** [comment]
running with --disk fixed my issue..looking forward to any improvements to the tool! Thanks!
