### ISSUE TITLE
can not run against list of urls

### ISSUE THREAD

**Issue by Sy3Omda** [zricethezav/gitleaks#383]
**Describe the bug**
I have list of git links and i want to run gitleaks against it but i did not find an argument to do so,
So i created a bash script to run gitleaks BUT when i use option --report= to generate a list of reports for each git repo separately it keeps gives error

**To Reproduce**
for line in $(cat testurls); do gitleaks --repo=$line --report=$line --verbose --pretty ; done

**Expected behavior**
A report file named with the line itself

**Error1**
```
goroutine 30 [IO wait]:
internal/poll.runtime_pollWait(0x7f938a558288, 0x72, 0xffffffffffffffff)
        /usr/local/go/src/runtime/netpoll.go:203 +0x55
internal/poll.(*pollDesc).wait(0xc0000f1b18, 0x72, 0xe400, 0xe421, 0xffffffffffffffff)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
        /usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0000f1b00, 0xc0005a0000, 0xe421, 0xe421, 0x0, 0x0, 0x0)
        /usr/local/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc0000f1b00, 0xc0005a0000, 0xe421, 0xe421, 0x203009, 0x8, 0x40dc06)
        /usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000010010, 0xc0005a0000, 0xe421, 0xe421, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:184 +0x8e
crypto/tls.(*atLeastReader).Read(0xc0263fe2a0, 0xc0005a0000, 0xe421, 0xe421, 0x7f938a549e40, 0x0, 0xc00004e918)
        /usr/local/go/src/crypto/tls/conn.go:760 +0x60
bytes.(*Buffer).ReadFrom(0xc000045758, 0xcadf80, 0xc0263fe2a0, 0x40bb55, 0xacfec0, 0xb9f140)
        /usr/local/go/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc000045500, 0xcaed40, 0xc000010010, 0x5, 0xc000010010, 0x100c0127b8018)
        /usr/local/go/src/crypto/tls/conn.go:782 +0xec
crypto/tls.(*Conn).readRecordOrCCS(0xc000045500, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:589 +0x115
crypto/tls.(*Conn).readRecord(...)
        /usr/local/go/src/crypto/tls/conn.go:557
crypto/tls.(*Conn).Read(0xc000045500, 0xc00030c000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:1233 +0x15b
net/http.(*persistConn).Read(0xc00013b9e0, 0xc00030c000, 0x1000, 0x1000, 0xc000189aa0, 0xc00004ec70, 0x406ab5)
        /usr/local/go/src/net/http/transport.go:1825 +0x75
bufio.(*Reader).fill(0xc0000b0960)
        /usr/local/go/src/bufio/bufio.go:100 +0x103
bufio.(*Reader).Peek(0xc0000b0960, 0x1, 0x0, 0x0, 0x1, 0xc000189c00, 0x0)
        /usr/local/go/src/bufio/bufio.go:138 +0x4f
net/http.(*persistConn).readLoop(0xc00013b9e0)
        /usr/local/go/src/net/http/transport.go:1978 +0x1a8

```
**Error2**
it did not print out the report result as wanted in new files !!

 - OS: Ubuntu 16.04

cc @zricethezav

**Comment by zricethezav** [comment]
I'm not seeing where the source of the error is from. Could you provide a more detailed error message?

**Comment by zricethezav** [comment]
Closing this as there hasn't been any activity on it in a while
