### ISSUE TITLE
Error message when adding Base64 regex

### ISSUE THREAD

**Issue by CargaisonTuba** [zricethezav/gitleaks#403]
**Describe the bug**
I implemented a Base64 regex to the rules, and this regex works on regex101.com on the "Go" setup, but here it doesn't work and I get an error message.

**To Reproduce**
add this to the default.go :
```
[[rules]]
	description = "Basic base64 regex"
	regex='''(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?'''
	tags = ["base64"]
```

**Expected behavior**
Find Base64 regex

**Screenshots**
No screenshot but here is the error message I get : 
```
➜  gitleaks git:(master) ✗ ./main --repo=./                                  
INFO[2020-07-01T09:21:16+02:00] cloning... ./                                
panic: runtime error: slice bounds out of range [66:65]

goroutine 1455 [running]:
github.com/zricethezav/gitleaks/v4/audit.inspectFileContents(0xc000fdd24e, 0x42, 0xc000a88c40, 0x11, 0xc0000c2bc0, 0x12, 0xc0001fef00, 0xc0001ff040, 0xc0001ff180, 0xc0001d4d70, ...)
	/home/pastequedeter/Downloads/gitleaks/audit/util.go:234 +0x3be
github.com/zricethezav/gitleaks/v4/audit.InspectFile(0xc000fdd24e, 0x42, 0xc000a88c40, 0x11, 0xc0034c2000, 0xc0001c00c0)
	/home/pastequedeter/Downloads/gitleaks/audit/util.go:202 +0x7ab
github.com/zricethezav/gitleaks/v4/audit.inspectPatch(0xc000a23f50, 0xc0034c2000, 0xc0001c00c0)
	/home/pastequedeter/Downloads/gitleaks/audit/util.go:37 +0x207
github.com/zricethezav/gitleaks/v4/audit.(*Repo).Audit.func1.1.2(0xc001c06a10, 0xc000441a30, 0xc0001c00c0, 0xc0034c2000, 0xc000a23f50)
	/home/pastequedeter/Downloads/gitleaks/audit/repo.go:328 +0x7a
created by github.com/zricethezav/gitleaks/v4/audit.(*Repo).Audit.func1.1
	/home/pastequedeter/Downloads/gitleaks/audit/repo.go:323 +0x2b6

```

**Basic Info (please complete the following information):**
 - OS: Ubuntu
 - Gitleaks Version: latest

cc @zricethezav

**Comment by CargaisonTuba** [comment]
Okay there was an error in the regex, solved now.
But another problem, I don't get how rules.exception work.
I've added this base64 regex but it detects MD5 so I added an exception like this : 
```
[[rules]]
	description = "Basic base64 regex"
	regex='''(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)'''
	tags = ["base64"]
	[[rules.whitelist]]
   		description = "MD5"
    		regex = '''[^a-f0-9-][a-f0-9]{32}[^a-f0-9-]'''
```
I understand it as "if I find a Base64 but it's also a MD5 then I don't detect it" but it does nothing and MD5 still get detected as Base64

**Comment by zricethezav** [comment]
Likely fixed in v8 reopen if not
