### ISSUE TITLE
"fatal error: concurrent map read and map write" when use threads

### ISSUE THREAD

**Issue by qingxp9** [zricethezav/gitleaks#518]
```
~/go/bin/gitleaks --path=./repo -v --config-path=./email.conf --threads=10 --report test.txt
```
after some normal outputs, it shows up an error
```
{
        "line": "* @xxxx ",
        "lineNumber": 20,
        "offender": "xxxx",
        "commit": "xxxxx",
        "repo": "xxx",
        "repoURL": "",
        "leakURL": "",
        "rule": "email",        
        "commitMessage": "",
        "author": "xxx",
        "email": "xxxxx.com",
        "file": "xxxxxxxx",
        "date": "2019-08-13T19:11:38+08:00",
        "tags": "xxxxx"
}
fatal error: concurrent map read and map write
fatal error: concurrent map writes

goroutine 237 [running]:
runtime.throw(0x90c8ec, 0x21)
        /usr/lib/golang/src/runtime/panic.go:1116 +0x72 fp=0xc0119adde8 sp=0xc0119addb8 pc=0x4376d2
runtime.mapaccess2_fast64(0x873740, 0xc00505eea0, 0x990971, 0x650209, 0xc007af8bf8)
        /usr/lib/golang/src/runtime/map_fast64.go:61 +0x1ac fp=0xc0119ade10 sp=0xc0119adde8 pc=0x4141$
c
github.com/go-git/go-git/v5/plumbing/format/idxfile.(*MemoryIndex).FindHash(0xc02994f600, 0x990971, 0$
0, 0x0, 0x717d042c00000000, 0x423b795ad30406b2, 0x690a7f0ec21be00f)
        /root/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/plumbing/format/idxfile/idxfile.go:176 +0$
1a5 fp=0xc0119ade70 sp=0xc0119ade10 pc=0x628485
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).decodeObjectAt(0xc007af8bf8, 0xc00401$
050, 0x990971, 0xc21be00f423b795a, 0x717d042c690a7f0e, 0x717d042cd30406b2, 0xc004018050)
        /root/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/storage/filesystem/object.go:455 +0x44 fp$
0xc0119adee0 sp=0xc0119ade70 pc=0x651fc4
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).getFromPackfile(0xc007af8bf8, 0x2e95c$
2bc3d34cb7, 0x5d8950be252c2cb4, 0xffffff0004653d6f, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/storage/filesystem/object.go:448 +0x2cd f$
=0xc0119adfd0 sp=0xc0119adee0 pc=0x651ded
github.com/go-git/go-git/v5/storage/filesystem.(*ObjectStorage).EncodedObject(0xc007af8bf8, 0x95cb2bc$
d34cb702, 0x8950be252c2cb42e, 0x7f04653d6f5d, 0x0, 0x0, 0x0, 0x0)
        /root/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/storage/filesystem/object.go:317 +0x6e fp$
0xc0119ae070 sp=0xc0119adfd0 pc=0x650eee
github.com/go-git/go-git/v5/plumbing/object.GetTree(0x7f4784225980, 0xc007af8be0, 0x2e95cb2bc3d34cb7, 
0x5d8950be252c2cb4, 0xc004653d6f, 0x4b6af95550cb7a91, 0xcb7aeb5198f2a590, 0xc0565e24ac)
        /root/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/plumbing/object/tree.go:45 +0x4e fp=0xc01$
9ae0c0 sp=0xc0119ae070 pc=0x60a9ae
github.com/go-git/go-git/v5/plumbing/object.(*Commit).Tree(...)
        /root/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/plumbing/object/commit.go:76
github.com/go-git/go-git/v5/plumbing/object.(*Commit).PatchContext(0xc01de480f0, 0x992300, 0xc0000260$
8, 0xc0239f64b0, 0x0, 0x6430663962366339, 0x3731343531323831)
        /root/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/plumbing/object/commit.go:85 +0x71 fp=0xc$
119ae140 sp=0xc0119ae0c0 pc=0x5fab71
github.com/go-git/go-git/v5/plumbing/object.(*Commit).Patch(...)
/root/go/pkg/mod/github.com/go-git/go-git/v5@v5.2.0/plumbing/object/commit.go:106
github.com/zricethezav/gitleaks/v7/scan.(*CommitScanner).Scan(0xc0119afd30, 0x0, 0x0, 0x7ffc52d6078c, 
0x5, 0x7ffc52d607a3, 0x17)
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/scan/commit.go:64 +0x14e fp=0xc011$
af6d0 sp=0xc0119ae140 pc=0x80df8e
github.com/zricethezav/gitleaks/v7/scan.(*RepoScanner).Scan.func2(0x0, 0x0)
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/scan/repo.go:88 +0x21a fp=0xc0119a$
f78 sp=0xc0119af6d0 pc=0x81c85a
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00505fd40, 0xc077dac980)
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57 
+0x59 fp=0xc0119affd0 sp=0xc0119aff78 pc=0x80d4b9
runtime.goexit()
        /usr/lib/golang/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0119affd8 sp=0xc0119affd0 pc=0x46c3c1
created by golang.org/x/sync/errgroup.(*Group).Go
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 
+0x66

goroutine 1 [chan receive]:
github.com/zricethezav/gitleaks/v7/scan.(*RepoScanner).Scan(0xc01f6f3680, 0xc0001964d6, 0x9, 0x7ffc52$
6078c, 0x5, 0x7ffc52d607a3, 0x17)
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/scan/repo.go:107 +0x4ba
github.com/zricethezav/gitleaks/v7/scan.(*ParentScanner).Scan(0xc0001de000, 0x1be51e, 0xbf74e0, 0x7ff$
52d6078c, 0x5, 0x7ffc52d607a3, 0x17)
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/scan/parent.go:67 +0x64b
main.main()
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/main.go:52 +0x43a

goroutine 18 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
        /usr/lib/golang/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
        /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
        /usr/lib/golang/src/os/signal/signal.go:150 +0x45

goroutine 19 [chan receive, 1 minutes]:
main.listenForInterrupt(0xc000074660)
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/main.go:71 +0x38
created by main.main
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/main.go:21 +0xce

goroutine 218 [semacquire]:
sync.runtime_Semacquire(0xc00505fd50)
        /usr/lib/golang/src/runtime/sema.go:56 +0x45
sync.(*WaitGroup).Wait(0xc00505fd48)
        /usr/lib/golang/src/sync/waitgroup.go:130 +0x65
golang.org/x/sync/errgroup.(*Group).Wait(0xc00505fd40, 0x0, 0x0)
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:40 
+0x31
github.com/zricethezav/gitleaks/v7/scan.(*RepoScanner).Scan.func3(0xc00505fd40, 0xc0001e1560)
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/scan/repo.go:101 +0x2f
created by github.com/zricethezav/gitleaks/v7/scan.(*RepoScanner).Scan
        /root/go/pkg/mod/github.com/zricethezav/gitleaks/v7@v7.2.0/scan/repo.go:100 +0x445

goroutine 293 [running]:
        goroutine running on other thread; stack unavailable
created by golang.org/x/sync/errgroup.(*Group).Go
        /root/go/pkg/mod/golang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:54 
+0x66
……
……
```

cc @zricethezav

**Comment by qingxp9** [comment]
after up to date, it works normally now.
