### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by johnjeffers** [zricethezav/gitleaks#752]
**Describe the bug**
`gitleaks detect` with no other options throws an `invalid memory address or nil pointer dereference` on some, but not all, of my repos. On some repos it works fine, on others it throws this or a similar error.

**To Reproduce**
run `gitleaks detect` on an affected repo

**Expected behavior**
`gitleaks detect` returns a result

**Screenshots**
```
» gitleaks detect

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x10 pc=0x100426028]

goroutine 34 [running]:
regexp.(*Regexp).allMatches(0x0, {0x0, 0x0}, {0x1400000a900, 0xf4, 0x100}, 0xf5, 0x14000287980)
	regexp/regexp.go:776 +0xa8
regexp.(*Regexp).FindAllIndex(0x0, {0x1400000a900, 0xf4, 0x100}, 0xffffffffffffffff)
	regexp/regexp.go:1099 +0x7c
github.com/zricethezav/gitleaks/v8/detect.DetectFindings({{0x140001de7f0, 0xe}, {0x0, 0x0}, {0x14000187480, 0xf, 0x10}, {{0x0, 0x0}, {0x0, ...}, ...}}, ...)
	github.com/zricethezav/gitleaks/v8/detect/detect.go:61 +0x4d8
github.com/zricethezav/gitleaks/v8/detect.FromGit.func1(0x140001de820, 0x14000130120, {0x0, 0x0}, 0x140001de810, 0x1400012e8b8, 0x14000130240)
	github.com/zricethezav/gitleaks/v8/detect/git.go:61 +0x244
created by github.com/zricethezav/gitleaks/v8/detect.FromGit
	github.com/zricethezav/gitleaks/v8/detect/git.go:30 +0x174
```

**Basic Info (please complete the following information):**
 - OS: macOS Monterey 12.1 on 2021 M1 Pro MacBook
 - Gitleaks Version: 8.2.1, installed via homebrew

**Additional context**

cc @zricethezav

**Comment by zricethezav** [comment]
@johnjeffers That is coming from https://github.com/zricethezav/gitleaks/blob/master/detect/detect.go#L61. I suppose that should be checked for nil.

Can you rerun with `--log-level=debug` and post your config that you are using?

**Comment by johnjeffers** [comment]
Well damn, it looks like there's an existing `.gitleaks.toml` in the repos where it's failing. So I'm sure that must be the problem. Sorry to bug you, and thanks for the quick response!

**Comment by zricethezav** [comment]
@johnjeffers thanks for opening this issue! The gitleaks config should be validated before continuing the program. If a rule is defined, it needs to have a `regex` or a `path` defined.

**Comment by crazy-matt** [comment]
@johnjeffers I was experiencing the same issue using the gitleaks docker image. Until I revisit my toml config file by validating rule by rule and find out that one of them was not using the correct syntax.
I tried:
`file = '''(.*?)(id_rsa|passwd|id_rsa.pub|pgpass|pem|ppk|key|shadow)$'''`

and then

`paths = ['''(.*?)(id_rsa|passwd|id_rsa.pub|pgpass|pem|ppk|key|shadow)$''']`

while I should have used

`path = '''(.*?)(id_rsa|passwd|id_rsa.pub|pgpass|pem|ppk|key|shadow)$'''`

If it can helps. 🤷🏽‍♂️
