### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by scilganon** [zricethezav/gitleaks#81]
### Error:

```
➜  Downloads ./gitleaks-linux-amd64 --repo-path=/home/projects/test 
INFO[2018-07-24T01:09:57+03:00] cloning                                      
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8c4fc5]

goroutine 1176 [running]:
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Patch).FilePatches(...)
	/Users/zach/Go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:125
main.auditRef.func1.1(0xc4201ac040, 0x0, 0x0, 0xc4200909c0, 0xc432bfc1e0, 0xc432bfc0f0)
	/Users/zach/Go/src/github.com/zricethezav/gitleaks/main.go:355 +0x55
created by main.auditRef.func1
	/Users/zach/Go/src/github.com/zricethezav/gitleaks/main.go:348 +0x1a0
```

### System:

```
➜  Downloads ./gitleaks-linux-amd64 --version
1.1.2
```

```
➜  Downloads uname -a
Linux NB-NIX 4.17.8-1-ARCH #1 SMP PREEMPT Wed Jul 18 09:56:24 UTC 2018 x86_64 GNU/Linux
```

---

have other repos, and it works with them

---

what else do you need?

**Comment by zricethezav** [comment]
hmm could be unbounded concurrency, try setting `--max-go=1`

**Comment by ljohnston** [comment]
I'm seeing the same thing also. Adding --max-go=1 either hangs or takes a _really_ long time. After about 30 minutes I aborted it.

**Comment by d47zm3** [comment]
For me (same version), --repo-path tries to clone repository to disk, why? 
```
root@host: tools [master]× » gitleaks --repo-path=/root/localrepo --max-go=1                                                                                                                                                                                    2 [09:17:19]
INFO[2018-08-09T09:17:35+02:00] cloning
panic: runtime error: index out of range

goroutine 6 [running]:
github.com/zricethezav/gitleaks/vendor/github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffCharsToLines(0xc420061b78, 0xc4203b4060, 0x1, 0x2, 0xc421046000, 0xe52e, 0xec00, 0xf000, 0xc4203b4060, 0x1)
        /root/go/src/github.com/zricethezav/gitleaks/vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go:414 +0x31d
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/diff.Do(0xc420e06000, 0x8573a, 0x0, 0x0, 0x0, 0x0, 0x0)
        /root/go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/diff/diff.go:21 +0x1b4
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.filePatchWithContext(0xa97a40, 0xc4200a0010, 0xc42051c780, 0xa96cc0, 0xc4200b35e0, 0x0, 0x0)
```

**Comment by zricethezav** [comment]
@d47zm3 its not cloning locally, just a badly placed log: https://github.com/zricethezav/gitleaks/blob/master/main.go#L269

**Comment by zricethezav** [comment]
@ljohnston @scilganon  looks like https://github.com/zricethezav/gitleaks/blob/master/main.go#L354 needs to be err checked

**Comment by zricethezav** [comment]
i can fix this up next week unless someone wants to get to them before. feel free to open a PR

**Comment by benjoz** [comment]
seems to have the same issue 

```
Enumerating objects: 35559, done.
Counting objects: 100% (35559/35559), done.
Compressing objects: 100% (15541/15541), done.
Total 35559 (delta 17459), reused 35033 (delta 17204)
panic: runtime error: index out of range

goroutine 18313 [running]:
github.com/zricethezav/gitleaks/vendor/github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffCharsToLines(0xc042869b70, 0xc06743aab0, 0x1, 0x2, 0xc085a26000, 0xe616, 0xec00, 0x0, 0xc06743aab0, 0x1)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/vendor/github.com/sergi/go-diff/diffmatchpatch/diff.go:414 +0x355
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/diff.Do(0x0, 0x0, 0xc0b27a2000, 0x476bf7, 0x0, 0x0, 0x0)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/utils/diff/diff.go:21 +0x1b4
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.filePatchWithContext(0x16dc300, 0xc0000aa008, 0xc03097bd00, 0x16db640, 0xc063830b40, 0x0, 0x0)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:68 +0x220
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.getPatchContext(0x16dc300, 0xc0000aa008, 0x0, 0x0, 0xc039294a00, 0xa81, 0xa81, 0xc035944140, 0xc0359441e0, 0x0)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:38 +0xd5
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.Changes.PatchContext(0xc039294a00, 0xa81, 0xa81, 0x16dc300, 0xc0000aa008, 0xa81, 0xa81, 0x0)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/change.go:156 +0x62
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Tree).PatchContext(0xc04a3468c0, 0x16dc300, 0xc0000aa008, 0xc035944140, 0x70736e6172742074, 0x207361772074726f, 0x45206e656b6f7262)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/tree.go:322 +0xb5
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).PatchContext(0xc00b2af2c0, 0x16dc300, 0xc0000aa008, 0xc00b2af1d0, 0x20656874203a6370, 0x697463656e6e6f63, 0x6c63207369206e6f)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:91 +0xb5
github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).Patch(0xc00b2af2c0, 0xc00b2af1d0, 0x74726f70736e6172, 0x2064656c69616620, 0x7461657263206f74)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/vendor/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:96 +0x4d
main.auditRef.func1.1(0xc022799000, 0x0, 0xc00ad4db00, 0xc0002b0380, 0xc00b2af2c0, 0xc00b2af1d0)
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/main.go:363 +0x50
created by main.auditRef.func1
	/Users/benjamin/go/src/github.com/zricethezav/gitleaks/main.go:357 +0x19c
```

**Comment by zricethezav** [comment]
@benjoz @d47zm3 @scilganon I ran into this issue when performing some audits on large repos. Seems that other folks outside this project have also ran into it https://github.com/sergi/go-diff/issues/89. Go-git, which gitleaks depends on, uses sergi/go-diff. I'll try and see if I can get a branch that resolves this, or at least handles the panic

**Comment by zricethezav** [comment]
https://github.com/zricethezav/gitleaks/releases/tag/v1.6.1 should fix this. Give me a 👍 and ill close this issue out. NOTE: the panic does cause gitleaks to skip checking the diff on the troubled commit

**Comment by zricethezav** [comment]
closing this
