### ISSUE TITLE
Slice bounds out of range panic in v8.7.0 detect.(*Detector).Detect()

### ISSUE THREAD

**Issue by aaron42net** [zricethezav/gitleaks#842]
When running v8.7.0 `gitleaks detect -s .` against my repo, I get this panic in `detect.(*Detector).Detect()` line 398:
```
panic: runtime error: slice bounds out of range [:46557] with length 27978

goroutine 1234141 [running]:
github.com/zricethezav/gitleaks/v8/detect.(*Detector).Detect(0x14000138100, {{0x140039e8000, 0x6d4a}, {0x1400d33a6c0, 0x31}, {0x14012cfb4a7, 0x28}, {0x140035dd000, 0x35, 0x55}, ...})
        github.com/zricethezav/gitleaks/v8@v8.7.0/detect/detect.go:398 +0x59c
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectGit.func1()
        github.com/zricethezav/gitleaks/v8@v8.7.0/detect/detect.go:305 +0x114
github.com/fatih/semgroup.(*Group).Go.func1(0x140001000f0, 0x1400386f020)
        github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0x90
created by github.com/fatih/semgroup.(*Group).Go
        github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x2c4
```

`d.prefilter.FindAll()` is run on the output of `strings.ToLower()`, while the slice operation is not.  `strings.ToLower()` is Unicode-aware. Perhaps it changed the length of the string.  I'd maybe suggest running `strings.ToLower(fragment.Raw)` once here and passing the result to both `d.prefilter.FindAll()` and the slice operation.

This code appears to have been just added in https://github.com/zricethezav/gitleaks/pull/841.

**Comment by zricethezav** [comment]
@aaron42net thanks for raising this issue. Could you check if the changes pushed here https://github.com/zricethezav/gitleaks/tree/fix-842 fix your issue?

**Comment by wjessop** [comment]
I had the same issue. I built master and still get the issue:

```
$ ../gitleaks/gitleaks detect 

    ○
    │╲
    │ ○
    ○ ░
    ░    gitleaks 

panic: runtime error: slice bounds out of range [:118219] with length 117816

goroutine 37204 [running]:
github.com/zricethezav/gitleaks/v8/detect.(*Detector).Detect(0xc0001a2100, {{0xc0127e4000, 0x1cc38}, {0xc00e3e82c0, 0x38}, {0xc00f4cb387, 0x28}, {0xc00e37a800, 0x38, 0x55}, ...})
	/Users/will/clients/Outvote/repos/gitleaks/detect/detect.go:398 +0x5c5
github.com/zricethezav/gitleaks/v8/detect.(*Detector).DetectGit.func1()
	/Users/will/clients/Outvote/repos/gitleaks/detect/detect.go:305 +0x1b8
github.com/fatih/semgroup.(*Group).Go.func1()
	/Users/will/www/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:64 +0xa2
created by github.com/fatih/semgroup.(*Group).Go
	/Users/will/www/go/pkg/mod/github.com/fatih/semgroup@v1.2.0/semgroup.go:60 +0x23e
```


```
$ cat ../gitleaks/.git/HEAD 
ref: refs/heads/master
```

**Comment by zricethezav** [comment]
@wjessop can you try building from this branch: https://github.com/zricethezav/gitleaks/tree/fix-842 and letting me know if it is still an issue?

**Comment by wjessop** [comment]
Yup, that worked, thanks!
